export type AwesomeItem = { name: string; description: string; href: string };
export type AwesomeCategory = {
  slug: string;
  emoji: string;
  title: string;
  description: string;
  items: readonly AwesomeItem[];
};

export const AWESOME_CATEGORIES = [
  {
    slug: "setup",
    emoji: "⚙️",
    title: "Environment",
    description: "Get your environment ready before writing a single line of code.",
    items: [
      { name: "Cursor", description: "The most advanced AI-first code editor, recommended starting point.", href: "https://cursor.com" },
      { name: "VS Code", description: "Free, extensible editor with strong AI plugin support.", href: "https://code.visualstudio.com" },
      { name: "GitHub", description: "Create your repo before writing any code, not after.", href: "https://github.com" },
      { name: "Node.js", description: "LTS version only, install this before starting any web project.", href: "https://nodejs.org" },
      { name: "Warp", description: "AI-native terminal that understands your commands.", href: "https://warp.dev" },
      { name: "Homebrew", description: "The missing package manager for macOS and Linux.", href: "https://brew.sh" },
    ],
  },
  {
    slug: "research-validate",
    emoji: "🔍",
    title: "Research",
    description: "Prove the idea before writing a line of code.",
    items: [
      { name: "Perplexity", description: "Deep research AI, ask anything, get sourced answers fast.", href: "https://perplexity.ai" },
      { name: "Google Trends", description: "Check real search demand before you build.", href: "https://trends.google.com" },
      { name: "Product Hunt", description: "Discover what's already out there and validate your angle.", href: "https://producthunt.com" },
      { name: "Indie Hackers", description: "Builder community, see what's working for others.", href: "https://indiehackers.com" },
      { name: "r/vibecoding", description: "Active community of AI-first builders sharing what ships.", href: "https://reddit.com/r/vibecoding" },
      { name: "r/SideProject", description: "Post your idea, get early brutally honest feedback.", href: "https://reddit.com/r/SideProject" },
      { name: "Similar Web", description: "Estimate competitor traffic and audience size.", href: "https://similarweb.com" },
      { name: "Typeform", description: "Run quick user surveys to validate assumptions before building.", href: "https://typeform.com" },
      { name: "YC Startup Library", description: "Essays and frameworks on what makes ideas worth building.", href: "https://ycombinator.com/library" },
      { name: "Karpathy on vibe coding", description: "The original post that named and defined the mindset.", href: "https://x.com/karpathy" },
    ],
  },
  {
    slug: "prd-spec",
    emoji: "📋",
    title: "PRD",
    description: "Turn ideas into structured specs and tracked tasks.",
    items: [
      { name: "Claude Task Master", description: "Breaks a spec into structured subtasks for AI to execute.", href: "https://github.com/eyaltoledano/claude-task-master" },
      { name: "Boomerang Tasks", description: "Turns big ideas into prioritized task queues automatically.", href: "https://github.com/GreatScottGadgets/boomerang" },
      { name: "CodeGuide", description: "Builds living documentation for AI-driven projects.", href: "https://codeguide.dev" },
      { name: "Linear", description: "Structured issue tracking built for fast-moving teams.", href: "https://linear.app" },
      { name: "Notion", description: "Write and version your PRD in a shareable, searchable doc.", href: "https://notion.so" },
      { name: "Whimsical", description: "Fast flowcharts and user journey diagrams.", href: "https://whimsical.com" },
      { name: "Miro", description: "Visual user story mapping and scope planning.", href: "https://miro.com" },
      { name: "Loom", description: "Record async walkthroughs of your spec for collaborators.", href: "https://loom.com" },
      { name: "GitHub Issues", description: "Lightweight spec tracking directly in your repo.", href: "https://github.com" },
    ],
  },
  {
    slug: "architecture-stack",
    emoji: "🏗️",
    title: "Stack",
    description: "The stack decisions and infrastructure that power vibe coding.",
    items: [
      { name: "Next.js", description: "The default React framework for production web apps.", href: "https://nextjs.org" },
      { name: "Tailwind CSS", description: "Utility-first CSS, fast to write, easy for AI to generate.", href: "https://tailwindcss.com" },
      { name: "shadcn/ui", description: "Copy-paste component library that owns its own code.", href: "https://ui.shadcn.com" },
      { name: "Supabase", description: "Postgres backend with auth, storage, and realtime built in.", href: "https://supabase.com" },
      { name: "Neon", description: "Serverless Postgres, scales to zero, great for solo projects.", href: "https://neon.tech" },
      { name: "Clerk", description: "Drop-in auth with social logins, MFA, and user management.", href: "https://clerk.com" },
      { name: "Drizzle", description: "Lightweight type-safe SQL ORM that pairs well with AI codegen.", href: "https://orm.drizzle.team" },
      { name: "Prisma", description: "Type-safe ORM with a great DX and schema-first workflow.", href: "https://prisma.io" },
      { name: "Upstash", description: "Serverless Redis for rate limiting, queues, and caching.", href: "https://upstash.com" },
      { name: "Resend", description: "Transactional email API built for developers.", href: "https://resend.com" },
      { name: "v0", description: "Generate UI components from natural language descriptions.", href: "https://v0.dev" },
      { name: "Figma", description: "Wireframe and prototype the UX before any code is written.", href: "https://figma.com" },
      { name: "Framer", description: "Design and publish production sites without writing CSS.", href: "https://framer.com" },
    ],
  },
  {
    slug: "agent-setup",
    emoji: "🤖",
    title: "Context",
    description: "AI coding agents, editors, and models, set them up right.",
    items: [
      { name: "Claude Code", description: "Works across codebases, explains code, and automates tasks from the terminal.", href: "https://claude.ai/code" },
      { name: "Cursor", description: "The most advanced AI-first code editor available.", href: "https://cursor.com" },
      { name: "Windsurf", description: "AI-focused IDE by Codeium with deep context awareness.", href: "https://windsurf.ai" },
      { name: "Zed", description: "Blazing-fast AI-native editor built for collaborative coding.", href: "https://zed.dev" },
      { name: "Trae", description: "Free Cursor alternative by ByteDance, fast and capable.", href: "https://trae.ai" },
      { name: "Cline", description: "Connects to your CLI and editor, interprets natural commands.", href: "https://github.com/cline/cline" },
      { name: "Roo Code", description: "Enhanced fork of Cline with extended agentic capabilities.", href: "https://github.com/RooVetGit/Roo-Code" },
      { name: "Continue", description: "Build custom in-editor AI agents using plugins and rules.", href: "https://continue.dev" },
      { name: "Augment Code", description: "Tailored for navigating and working in large repositories.", href: "https://augmentcode.com" },
      { name: "GitHub Copilot", description: "Context-aware suggestions, chat, and code actions in any editor.", href: "https://github.com/features/copilot" },
      { name: "avante.nvim", description: "Cursor-style AI assistance inside Neovim.", href: "https://github.com/yetone/avante.nvim" },
      { name: "Anthropic (Claude)", description: "Claude API, best for coding, reasoning, and long context tasks.", href: "https://anthropic.com" },
      { name: "OpenAI", description: "GPT-4o and o-series models, broad ecosystem and tooling.", href: "https://platform.openai.com" },
      { name: "Google AI Studio", description: "Gemini models with free tier and multimodal support.", href: "https://aistudio.google.com" },
      { name: "Groq", description: "Fastest inference available, great for low-latency apps.", href: "https://groq.com" },
      { name: "OpenRouter", description: "One API key, access to every major model, with fallbacks.", href: "https://openrouter.ai" },
    ],
  },
  {
    slug: "build-ship",
    emoji: "🚀",
    title: "Build",
    description: "From first prompt to real URL, platforms, deploy, and hosting.",
    items: [
      { name: "Bolt.new", description: "Prototype and launch full web apps entirely by prompting.", href: "https://bolt.new" },
      { name: "Lovable", description: "Full-stack applications generated from simple ideas.", href: "https://lovable.dev" },
      { name: "Firebase Studio", description: "Google's agent-driven full-stack development environment.", href: "https://firebase.studio" },
      { name: "Replit", description: "Type what you want, let AI construct it in the browser.", href: "https://replit.com" },
      { name: "Tempo", description: "Build React projects much faster through AI assistance.", href: "https://tempo.new" },
      { name: "aider", description: "Code side-by-side with AI directly from your terminal.", href: "https://aider.chat" },
      { name: "MyCoder.ai", description: "Modular AI coding agent with GitHub integration.", href: "https://mycoder.ai" },
      { name: "Goose", description: "Local agent framework compatible with multiple AI models.", href: "https://block.github.io/goose" },
      { name: "OpenAI Codex CLI", description: "Experimental terminal assistant from OpenAI.", href: "https://github.com/openai/codex" },
      { name: "Gemini CLI", description: "Terminal-based AI assistant powered by Google Gemini.", href: "https://github.com/google-gemini/gemini-cli" },
      { name: "Napkins", description: "Convert mockups or screenshots directly into working code.", href: "https://napkins.ai" },
      { name: "HeroUI Chat", description: "Build polished interfaces without design experience.", href: "https://heroui.chat" },
      { name: "Superdesign", description: "AI design agent for rapid UI iteration.", href: "https://superdesign.ai" },
      { name: "Vercel", description: "Zero-config frontend deployment with instant preview URLs.", href: "https://vercel.com" },
      { name: "Railway", description: "Deploy backends, workers, and databases without config.", href: "https://railway.app" },
      { name: "Render", description: "Full-stack hosting with auto-deploys from GitHub.", href: "https://render.com" },
      { name: "Fly.io", description: "Run containers close to your users globally.", href: "https://fly.io" },
      { name: "Netlify", description: "Serverless frontend deployment with edge functions.", href: "https://netlify.com" },
      { name: "Cloudflare Pages", description: "Edge-deployed frontend with Workers for serverless logic.", href: "https://pages.cloudflare.com" },
      { name: "Coolify", description: "Self-hosted Heroku/Netlify alternative, own your infra.", href: "https://coolify.io" },
    ],
  },
  {
    slug: "prompting-craft",
    emoji: "✨",
    title: "Prompting",
    description: "The models and SDKs you actually prompt, and how to reach them.",
    items: [
      { name: "Vercel AI SDK", description: "Unified TypeScript SDK for streaming from any AI provider.", href: "https://sdk.vercel.ai" },
      { name: "LangChain", description: "Framework for chaining LLM calls, tools, and memory.", href: "https://langchain.com" },
      { name: "Together AI", description: "Run open-source models at scale with a simple API.", href: "https://together.ai" },
      { name: "Replicate", description: "Deploy and run any open-source model with one API call.", href: "https://replicate.com" },
      { name: "Mistral", description: "Efficient open-weight models, strong at code and reasoning.", href: "https://mistral.ai" },
      { name: "VibePrompt", description: "Curated prompt library built for vibe coders, you're here.", href: "https://vibeprompt.tech" },
    ],
  },
  {
    slug: "testing-quality",
    emoji: "🛡️",
    title: "Quality",
    description: "AI can't self-correct, these gates are yours.",
    items: [
      { name: "Vitest", description: "Fast unit testing framework built for Vite and modern JS.", href: "https://vitest.dev" },
      { name: "Playwright", description: "End-to-end browser testing across all major browsers.", href: "https://playwright.dev" },
      { name: "Cypress", description: "Component and E2E testing with a great developer experience.", href: "https://cypress.io" },
      { name: "Biome", description: "Fast all-in-one linter and formatter, replaces ESLint + Prettier.", href: "https://biomejs.dev" },
      { name: "ESLint", description: "Catch bugs and enforce style before code is run.", href: "https://eslint.org" },
      { name: "GitHub Actions", description: "Run your test and build pipeline on every push.", href: "https://github.com/features/actions" },
      { name: "Sentry", description: "Catch errors in production before users report them.", href: "https://sentry.io" },
      { name: "Snyk", description: "Scan dependencies and code for security vulnerabilities.", href: "https://snyk.io" },
      { name: "Semgrep", description: "Static analysis rules you can write for your own codebase.", href: "https://semgrep.dev" },
      { name: "OWASP Top 10", description: "The security checklist every shipped app should pass.", href: "https://owasp.org/Top10" },
    ],
  },
  {
    slug: "launch-growth",
    emoji: "📣",
    title: "Ship",
    description: "Monetize, distribute, and close the loop with real users.",
    items: [
      { name: "Stripe", description: "The default payments API, subscriptions, one-time, and more.", href: "https://stripe.com" },
      { name: "Lemon Squeezy", description: "Merchant of record, handles VAT/tax so you don't have to.", href: "https://lemonsqueezy.com" },
      { name: "Paddle", description: "Another MoR option with global tax compliance built in.", href: "https://paddle.com" },
      { name: "Polar.sh", description: "Open-source monetization for developers, built for OSS.", href: "https://polar.sh" },
      { name: "PostHog", description: "Product analytics, session replay, and feature flags in one.", href: "https://posthog.com" },
      { name: "Plausible", description: "Simple, privacy-first web analytics, no cookie banners needed.", href: "https://plausible.io" },
      { name: "Mixpanel", description: "Event-based analytics to understand user behavior.", href: "https://mixpanel.com" },
      { name: "Hotjar", description: "Heatmaps and session recordings showing real user behavior.", href: "https://hotjar.com" },
      { name: "Canny", description: "Collect, organize, and prioritize user feature requests.", href: "https://canny.io" },
      { name: "Intercom", description: "In-app messaging to talk to users while they're in your product.", href: "https://intercom.com" },
      { name: "Tally", description: "Free Typeform alternative, beautiful forms, no limits.", href: "https://tally.so" },
      { name: "r/ChatGPTCoding", description: "AI dev community sharing real-world iteration stories.", href: "https://reddit.com/r/ChatGPTCoding" },
    ],
  },
  {
    slug: "backend",
    emoji: "🗄️",
    title: "Backend",
    description: "Databases, BaaS, and API infrastructure you'll need the moment your app has data.",
    items: [
      { name: "Supabase", description: "Postgres with auth, storage, realtime, and an instant REST API.", href: "https://supabase.com" },
      { name: "Neon", description: "Serverless Postgres that scales to zero — great for solo projects.", href: "https://neon.tech" },
      { name: "Convex", description: "Reactive backend-as-a-service with live queries and TypeScript-first DX.", href: "https://convex.dev" },
      { name: "Turso", description: "Edge SQLite database, deployed close to your users globally.", href: "https://turso.tech" },
      { name: "PlanetScale", description: "MySQL-compatible serverless database with branching like Git.", href: "https://planetscale.com" },
      { name: "MongoDB Atlas", description: "Flexible document database with a generous free tier.", href: "https://mongodb.com/atlas" },
      { name: "Firebase", description: "Google's BaaS — Firestore, Auth, Storage, and hosting in one.", href: "https://firebase.google.com" },
      { name: "Upstash", description: "Serverless Redis for caching, rate limiting, and queues.", href: "https://upstash.com" },
      { name: "tRPC", description: "End-to-end typesafe APIs without schema generation.", href: "https://trpc.io" },
      { name: "Hono", description: "Ultrafast edge-ready web framework, works on Cloudflare Workers.", href: "https://hono.dev" },
      { name: "Directus", description: "Headless CMS that wraps any SQL database with a REST/GraphQL API.", href: "https://directus.io" },
      { name: "Hasura", description: "Instant GraphQL API over your existing Postgres database.", href: "https://hasura.io" },
    ],
  },
  {
    slug: "monetization",
    emoji: "💳",
    title: "Monetization",
    description: "Accept payments, manage subscriptions, and handle tax compliance from day one.",
    items: [
      { name: "Stripe", description: "The default payments API — subscriptions, one-time, invoicing.", href: "https://stripe.com" },
      { name: "Lemon Squeezy", description: "Merchant of record — handles VAT and global tax so you don't have to.", href: "https://lemonsqueezy.com" },
      { name: "Paddle", description: "MoR with global tax compliance, great for SaaS with international users.", href: "https://paddle.com" },
      { name: "Polar.sh", description: "Open-source monetization built for developers and OSS projects.", href: "https://polar.sh" },
      { name: "Gumroad", description: "Sell digital products instantly with no code, great for early validation.", href: "https://gumroad.com" },
      { name: "Whop", description: "Sell access to communities, courses, SaaS, and digital products.", href: "https://whop.com" },
      { name: "Chargebee", description: "Subscription billing management and revenue recovery at scale.", href: "https://chargebee.com" },
      { name: "RevenueCat", description: "In-app purchase and subscription infrastructure for mobile apps.", href: "https://revenuecat.com" },
      { name: "Lago", description: "Open-source metered billing, usage-based pricing done right.", href: "https://getlago.com" },
    ],
  },
  {
    slug: "auth",
    emoji: "🔐",
    title: "Auth",
    description: "Authentication, authorization, and identity — don't build this yourself.",
    items: [
      { name: "Clerk", description: "Drop-in auth with social logins, MFA, orgs, and user management UI.", href: "https://clerk.com" },
      { name: "Auth.js", description: "Open-source authentication for Next.js and other frameworks.", href: "https://authjs.dev" },
      { name: "Supabase Auth", description: "Built-in auth in Supabase — email, OAuth, magic link, phone.", href: "https://supabase.com/auth" },
      { name: "WorkOS", description: "Enterprise SSO, SCIM, and audit logs — one API for all of it.", href: "https://workos.com" },
      { name: "Kinde", description: "Auth with a generous free tier, built for modern web apps.", href: "https://kinde.com" },
      { name: "Lucia", description: "Lightweight auth library — total control, no magic.", href: "https://lucia-auth.com" },
      { name: "Better Auth", description: "Comprehensive TypeScript auth framework, framework-agnostic.", href: "https://better-auth.com" },
      { name: "Stytch", description: "Passwordless auth — magic links, passkeys, OTP — with fraud protection.", href: "https://stytch.com" },
    ],
  },
  {
    slug: "email",
    emoji: "✉️",
    title: "Email",
    description: "Transactional email, newsletters, and marketing sends for your app.",
    items: [
      { name: "Resend", description: "Developer-first transactional email with React email templates.", href: "https://resend.com" },
      { name: "Loops", description: "Email for SaaS — transactional and marketing in one platform.", href: "https://loops.so" },
      { name: "Postmark", description: "Reliable transactional email with fast delivery and detailed analytics.", href: "https://postmarkapp.com" },
      { name: "SendGrid", description: "High-volume email infrastructure with marketing and transactional APIs.", href: "https://sendgrid.com" },
      { name: "Mailchimp", description: "Marketing email and audience management, with a free tier.", href: "https://mailchimp.com" },
      { name: "React Email", description: "Build HTML emails with React components, works with any provider.", href: "https://react.email" },
      { name: "Brevo", description: "Email + SMS + WhatsApp marketing, affordable and EU-based.", href: "https://brevo.com" },
    ],
  },
  {
    slug: "ops-maintenance",
    emoji: "⚙️",
    title: "Iterate",
    description: "Observability, reliability, and ops after you ship.",
    items: [
      { name: "BetterStack", description: "Uptime monitoring, log management, and incident alerts.", href: "https://betterstack.com" },
      { name: "Axiom", description: "Structured log management built for modern serverless apps.", href: "https://axiom.co" },
      { name: "Datadog", description: "Infrastructure and application monitoring at scale.", href: "https://datadog.com" },
      { name: "Umami", description: "Open-source, self-hostable privacy-friendly web analytics.", href: "https://umami.is" },
      { name: "GitHub Actions", description: "Automate workflows, deploys, and maintenance tasks.", href: "https://github.com/features/actions" },
      { name: "Cloudflare", description: "DDoS protection, caching, and edge networking at scale.", href: "https://cloudflare.com" },
    ],
  },
] as const satisfies readonly AwesomeCategory[];

