export type AwesomeItem = { name: string; description: string; href: string; tags: readonly string[] };
export type AwesomeCategory = {
  slug: string;
  emoji: string;
  title: string;
  description: string;
  items: readonly AwesomeItem[];
};

export const AWESOME_CATEGORIES = [
  {
    slug: "setup",
    emoji: "⚙️",
    title: "Environment",
    description: "Get your environment ready before writing a single line of code.",
    items: [
      { name: "Cursor", description: "The most advanced AI-first code editor, recommended starting point.", href: "https://cursor.com", tags: ["editor", "ai", "ide", "paid"] },
      { name: "VS Code", description: "Free, extensible editor with strong AI plugin support.", href: "https://code.visualstudio.com", tags: ["editor", "free", "open-source", "ide"] },
      { name: "GitHub", description: "Create your repo before writing any code, not after.", href: "https://github.com", tags: ["git", "free", "hosting", "open-source"] },
      { name: "Node.js", description: "LTS version only, install this before starting any web project.", href: "https://nodejs.org", tags: ["runtime", "free", "open-source", "javascript"] },
      { name: "Warp", description: "AI-native terminal that understands your commands.", href: "https://warp.dev", tags: ["terminal", "ai", "free", "macos"] },
      { name: "Homebrew", description: "The missing package manager for macOS and Linux.", href: "https://brew.sh", tags: ["package-manager", "free", "open-source", "macos"] },
    ],
  },
  {
    slug: "research-validate",
    emoji: "🔍",
    title: "Research",
    description: "Prove the idea before writing a line of code.",
    items: [
      { name: "Perplexity", description: "Deep research AI, ask anything, get sourced answers fast.", href: "https://perplexity.ai", tags: ["ai", "search", "free-tier"] },
      { name: "Google Trends", description: "Check real search demand before you build.", href: "https://trends.google.com", tags: ["analytics", "free", "seo", "google"] },
      { name: "Product Hunt", description: "Discover what's already out there and validate your angle.", href: "https://producthunt.com", tags: ["community", "free", "marketing", "launch"] },
      { name: "Indie Hackers", description: "Builder community, see what's working for others.", href: "https://indiehackers.com", tags: ["community", "free", "indie", "saas"] },
      { name: "r/vibecoding", description: "Active community of AI-first builders sharing what ships.", href: "https://reddit.com/r/vibecoding", tags: ["community", "free", "reddit", "ai"] },
      { name: "r/SideProject", description: "Post your idea, get early brutally honest feedback.", href: "https://reddit.com/r/SideProject", tags: ["community", "free", "reddit", "indie"] },
      { name: "Similar Web", description: "Estimate competitor traffic and audience size.", href: "https://similarweb.com", tags: ["analytics", "free-tier", "seo", "research"] },
      { name: "Typeform", description: "Run quick user surveys to validate assumptions before building.", href: "https://typeform.com", tags: ["forms", "surveys", "free-tier", "research"] },
      { name: "YC Startup Library", description: "Essays and frameworks on what makes ideas worth building.", href: "https://ycombinator.com/library", tags: ["learning", "free", "startup", "essays"] },
      { name: "Karpathy on vibe coding", description: "The original post that named and defined the mindset.", href: "https://x.com/karpathy", tags: ["learning", "free", "ai", "vibe-coding"] },
    ],
  },
  {
    slug: "prd-spec",
    emoji: "📋",
    title: "PRD",
    description: "Turn ideas into structured specs and tracked tasks.",
    items: [
      { name: "Claude Task Master", description: "Breaks a spec into structured subtasks for AI to execute.", href: "https://github.com/eyaltoledano/claude-task-master", tags: ["ai", "open-source", "free", "tasks", "planning"] },
      { name: "Boomerang Tasks", description: "Turns big ideas into prioritized task queues automatically.", href: "https://github.com/GreatScottGadgets/boomerang", tags: ["ai", "open-source", "free", "tasks"] },
      { name: "CodeGuide", description: "Builds living documentation for AI-driven projects.", href: "https://codeguide.dev", tags: ["docs", "ai", "paid", "planning"] },
      { name: "Linear", description: "Structured issue tracking built for fast-moving teams.", href: "https://linear.app", tags: ["project-management", "free-tier", "paid", "issues"] },
      { name: "Notion", description: "Write and version your PRD in a shareable, searchable doc.", href: "https://notion.so", tags: ["docs", "free-tier", "wiki", "planning"] },
      { name: "Whimsical", description: "Fast flowcharts and user journey diagrams.", href: "https://whimsical.com", tags: ["diagrams", "free-tier", "wireframes", "planning"] },
      { name: "Miro", description: "Visual user story mapping and scope planning.", href: "https://miro.com", tags: ["diagrams", "free-tier", "planning", "whiteboard"] },
      { name: "Loom", description: "Record async walkthroughs of your spec for collaborators.", href: "https://loom.com", tags: ["video", "free-tier", "async", "communication"] },
      { name: "GitHub Issues", description: "Lightweight spec tracking directly in your repo.", href: "https://github.com", tags: ["free", "open-source", "project-management", "issues"] },
    ],
  },
  {
    slug: "architecture-stack",
    emoji: "🏗️",
    title: "Stack",
    description: "The stack decisions and infrastructure that power vibe coding.",
    items: [
      { name: "Next.js", description: "The default React framework for production web apps.", href: "https://nextjs.org", tags: ["react", "framework", "free", "open-source", "typescript"] },
      { name: "Tailwind CSS", description: "Utility-first CSS, fast to write, easy for AI to generate.", href: "https://tailwindcss.com", tags: ["css", "free", "open-source", "ui"] },
      { name: "shadcn/ui", description: "Copy-paste component library that owns its own code.", href: "https://ui.shadcn.com", tags: ["ui", "free", "open-source", "react", "components"] },
      { name: "Supabase", description: "Postgres backend with auth, storage, and realtime built in.", href: "https://supabase.com", tags: ["database", "postgres", "free-tier", "open-source", "auth"] },
      { name: "Neon", description: "Serverless Postgres, scales to zero, great for solo projects.", href: "https://neon.tech", tags: ["database", "postgres", "serverless", "free-tier"] },
      { name: "Drizzle", description: "Lightweight type-safe SQL ORM that pairs well with AI codegen.", href: "https://orm.drizzle.team", tags: ["orm", "free", "open-source", "typescript", "sql"] },
      { name: "Prisma", description: "Type-safe ORM with a great DX and schema-first workflow.", href: "https://prisma.io", tags: ["orm", "free", "open-source", "typescript", "sql"] },
      { name: "Upstash", description: "Serverless Redis for rate limiting, queues, and caching.", href: "https://upstash.com", tags: ["redis", "serverless", "free-tier", "caching", "queues"] },
      { name: "Resend", description: "Transactional email API built for developers.", href: "https://resend.com", tags: ["email", "api", "free-tier", "transactional"] },
      { name: "v0", description: "Generate UI components from natural language descriptions.", href: "https://v0.dev", tags: ["ui", "ai", "free-tier", "components", "react"] },
      { name: "Figma", description: "Wireframe and prototype the UX before any code is written.", href: "https://figma.com", tags: ["design", "free-tier", "wireframes", "ui", "prototyping"] },
      { name: "Framer", description: "Design and publish production sites without writing CSS.", href: "https://framer.com", tags: ["design", "nocode", "free-tier", "website"] },
    ],
  },
  {
    slug: "agent-setup",
    emoji: "🤖",
    title: "Context",
    description: "AI coding agents, editors, and models, set them up right.",
    items: [
      { name: "Claude Code", description: "Works across codebases, explains code, and automates tasks from the terminal.", href: "https://claude.ai/code", tags: ["ai", "terminal", "cli", "anthropic", "free-tier"] },
      { name: "Cursor", description: "The most advanced AI-first code editor available.", href: "https://cursor.com", tags: ["editor", "ai", "ide", "paid"] },
      { name: "Windsurf", description: "AI-focused IDE by Codeium with deep context awareness.", href: "https://windsurf.ai", tags: ["editor", "ai", "ide", "free-tier"] },
      { name: "Zed", description: "Blazing-fast AI-native editor built for collaborative coding.", href: "https://zed.dev", tags: ["editor", "ai", "free", "open-source", "ide"] },
      { name: "Trae", description: "Free Cursor alternative by ByteDance, fast and capable.", href: "https://trae.ai", tags: ["editor", "ai", "free", "ide"] },
      { name: "Cline", description: "Connects to your CLI and editor, interprets natural commands.", href: "https://github.com/cline/cline", tags: ["ai", "open-source", "free", "terminal", "vscode"] },
      { name: "Roo Code", description: "Enhanced fork of Cline with extended agentic capabilities.", href: "https://github.com/RooVetGit/Roo-Code", tags: ["ai", "open-source", "free", "terminal", "agent"] },
      { name: "Continue", description: "Build custom in-editor AI agents using plugins and rules.", href: "https://continue.dev", tags: ["ai", "open-source", "free", "ide", "agent"] },
      { name: "Augment Code", description: "Tailored for navigating and working in large repositories.", href: "https://augmentcode.com", tags: ["ai", "paid", "ide", "large-codebase"] },
      { name: "GitHub Copilot", description: "Context-aware suggestions, chat, and code actions in any editor.", href: "https://github.com/features/copilot", tags: ["ai", "paid", "ide", "github"] },
      { name: "avante.nvim", description: "Cursor-style AI assistance inside Neovim.", href: "https://github.com/yetone/avante.nvim", tags: ["neovim", "ai", "open-source", "free", "vim"] },
      { name: "Anthropic (Claude)", description: "Claude API, best for coding, reasoning, and long context tasks.", href: "https://anthropic.com", tags: ["ai", "llm", "api", "paid", "free-tier"] },
      { name: "OpenAI", description: "GPT-4o and o-series models, broad ecosystem and tooling.", href: "https://platform.openai.com", tags: ["ai", "llm", "api", "paid", "free-tier"] },
      { name: "Google AI Studio", description: "Gemini models with free tier and multimodal support.", href: "https://aistudio.google.com", tags: ["ai", "llm", "free-tier", "google", "multimodal"] },
      { name: "Groq", description: "Fastest inference available, great for low-latency apps.", href: "https://groq.com", tags: ["ai", "llm", "api", "free-tier", "fast"] },
      { name: "OpenRouter", description: "One API key, access to every major model, with fallbacks.", href: "https://openrouter.ai", tags: ["ai", "llm", "api", "free-tier", "multi-model"] },
    ],
  },
  {
    slug: "build-ship",
    emoji: "🚀",
    title: "Build",
    description: "From first prompt to real URL, platforms, deploy, and hosting.",
    items: [
      { name: "Bolt.new", description: "Prototype and launch full web apps entirely by prompting.", href: "https://bolt.new", tags: ["ai", "nocode", "free-tier", "fullstack"] },
      { name: "Lovable", description: "Full-stack applications generated from simple ideas.", href: "https://lovable.dev", tags: ["ai", "nocode", "paid", "free-tier", "fullstack"] },
      { name: "Firebase Studio", description: "Google's agent-driven full-stack development environment.", href: "https://firebase.studio", tags: ["ai", "google", "free-tier", "fullstack"] },
      { name: "Replit", description: "Type what you want, let AI construct it in the browser.", href: "https://replit.com", tags: ["ai", "browser", "free-tier", "fullstack"] },
      { name: "Tempo", description: "Build React projects much faster through AI assistance.", href: "https://tempo.new", tags: ["ai", "react", "paid", "free-tier"] },
      { name: "aider", description: "Code side-by-side with AI directly from your terminal.", href: "https://aider.chat", tags: ["ai", "terminal", "open-source", "free"] },
      { name: "MyCoder.ai", description: "Modular AI coding agent with GitHub integration.", href: "https://mycoder.ai", tags: ["ai", "agent", "terminal", "paid"] },
      { name: "Goose", description: "Local agent framework compatible with multiple AI models.", href: "https://block.github.io/goose", tags: ["ai", "terminal", "open-source", "free", "agent"] },
      { name: "OpenAI Codex CLI", description: "Experimental terminal assistant from OpenAI.", href: "https://github.com/openai/codex", tags: ["ai", "terminal", "open-source", "free", "openai"] },
      { name: "Gemini CLI", description: "Terminal-based AI assistant powered by Google Gemini.", href: "https://github.com/google-gemini/gemini-cli", tags: ["ai", "terminal", "open-source", "free", "google"] },
      { name: "Napkins", description: "Convert mockups or screenshots directly into working code.", href: "https://napkins.ai", tags: ["ai", "design-to-code", "free-tier"] },
      { name: "HeroUI Chat", description: "Build polished interfaces without design experience.", href: "https://heroui.chat", tags: ["ai", "ui", "free-tier", "react"] },
      { name: "Superdesign", description: "AI design agent for rapid UI iteration.", href: "https://superdesign.ai", tags: ["ai", "design", "ui", "paid"] },
      { name: "Vercel", description: "Zero-config frontend deployment with instant preview URLs.", href: "https://vercel.com", tags: ["hosting", "serverless", "free-tier", "deployment", "frontend"] },
      { name: "Railway", description: "Deploy backends, workers, and databases without config.", href: "https://railway.app", tags: ["hosting", "deployment", "paid", "free-tier", "backend"] },
      { name: "Render", description: "Full-stack hosting with auto-deploys from GitHub.", href: "https://render.com", tags: ["hosting", "deployment", "free-tier", "fullstack"] },
      { name: "Fly.io", description: "Run containers close to your users globally.", href: "https://fly.io", tags: ["hosting", "containers", "paid", "free-tier", "global"] },
      { name: "Netlify", description: "Serverless frontend deployment with edge functions.", href: "https://netlify.com", tags: ["hosting", "serverless", "free-tier", "frontend", "edge"] },
      { name: "Cloudflare Pages", description: "Edge-deployed frontend with Workers for serverless logic.", href: "https://pages.cloudflare.com", tags: ["hosting", "edge", "free-tier", "frontend", "serverless"] },
      { name: "Coolify", description: "Self-hosted Heroku/Netlify alternative, own your infra.", href: "https://coolify.io", tags: ["self-hosted", "open-source", "free", "deployment"] },
    ],
  },
  {
    slug: "prompting-craft",
    emoji: "✨",
    title: "Prompting",
    description: "The models and SDKs you actually prompt, and how to reach them.",
    items: [
      { name: "Vercel AI SDK", description: "Unified TypeScript SDK for streaming from any AI provider.", href: "https://sdk.vercel.ai", tags: ["typescript", "api", "open-source", "free", "streaming"] },
      { name: "LangChain", description: "Framework for chaining LLM calls, tools, and memory.", href: "https://langchain.com", tags: ["python", "javascript", "open-source", "free", "framework"] },
      { name: "Together AI", description: "Run open-source models at scale with a simple API.", href: "https://together.ai", tags: ["ai", "llm", "api", "paid", "free-tier", "open-source"] },
      { name: "Replicate", description: "Deploy and run any open-source model with one API call.", href: "https://replicate.com", tags: ["ai", "api", "paid", "open-source", "models"] },
      { name: "Mistral", description: "Efficient open-weight models, strong at code and reasoning.", href: "https://mistral.ai", tags: ["ai", "llm", "open-source", "free-tier", "code"] },
      { name: "vibeprompt", description: "Curated prompt library built for vibe coders, you're here.", href: "https://vibeprompt.tech", tags: ["prompts", "free", "open-source", "vibe-coding"] },
    ],
  },
  {
    slug: "testing-quality",
    emoji: "🛡️",
    title: "Quality",
    description: "AI can't self-correct, these gates are yours.",
    items: [
      { name: "Vitest", description: "Fast unit testing framework built for Vite and modern JS.", href: "https://vitest.dev", tags: ["testing", "open-source", "free", "typescript", "unit"] },
      { name: "Playwright", description: "End-to-end browser testing across all major browsers.", href: "https://playwright.dev", tags: ["testing", "e2e", "open-source", "free", "browser"] },
      { name: "Cypress", description: "Component and E2E testing with a great developer experience.", href: "https://cypress.io", tags: ["testing", "e2e", "free-tier", "browser"] },
      { name: "Biome", description: "Fast all-in-one linter and formatter, replaces ESLint + Prettier.", href: "https://biomejs.dev", tags: ["linting", "formatting", "open-source", "free", "typescript"] },
      { name: "ESLint", description: "Catch bugs and enforce style before code is run.", href: "https://eslint.org", tags: ["linting", "open-source", "free", "javascript"] },
      { name: "GitHub Actions", description: "Run your test and build pipeline on every push.", href: "https://github.com/features/actions", tags: ["ci-cd", "free-tier", "automation", "github"] },
      { name: "Sentry", description: "Catch errors in production before users report them.", href: "https://sentry.io", tags: ["monitoring", "errors", "free-tier", "open-source"] },
      { name: "Snyk", description: "Scan dependencies and code for security vulnerabilities.", href: "https://snyk.io", tags: ["security", "free-tier", "dependencies", "scanning"] },
      { name: "Semgrep", description: "Static analysis rules you can write for your own codebase.", href: "https://semgrep.dev", tags: ["security", "open-source", "free", "static-analysis"] },
      { name: "OWASP Top 10", description: "The security checklist every shipped app should pass.", href: "https://owasp.org/Top10", tags: ["security", "free", "learning", "checklist"] },
    ],
  },
  {
    slug: "launch-growth",
    emoji: "📣",
    title: "Ship",
    description: "Monetize, distribute, and close the loop with real users.",
    items: [
      { name: "Stripe", description: "The default payments API, subscriptions, one-time, and more.", href: "https://stripe.com", tags: ["payments", "subscriptions", "api", "free-tier"] },
      { name: "Lemon Squeezy", description: "Merchant of record, handles VAT/tax so you don't have to.", href: "https://lemonsqueezy.com", tags: ["payments", "tax", "saas", "digital-products"] },
      { name: "Paddle", description: "Another MoR option with global tax compliance built in.", href: "https://paddle.com", tags: ["payments", "tax", "saas", "subscriptions"] },
      { name: "Polar.sh", description: "Open-source monetization for developers, built for OSS.", href: "https://polar.sh", tags: ["payments", "open-source", "free", "developers"] },
      { name: "PostHog", description: "Product analytics, session replay, and feature flags in one.", href: "https://posthog.com", tags: ["analytics", "open-source", "free-tier", "feature-flags", "session-replay"] },
      { name: "Plausible", description: "Simple, privacy-first web analytics, no cookie banners needed.", href: "https://plausible.io", tags: ["analytics", "privacy", "open-source", "free-tier"] },
      { name: "Mixpanel", description: "Event-based analytics to understand user behavior.", href: "https://mixpanel.com", tags: ["analytics", "paid", "free-tier", "events"] },
      { name: "Hotjar", description: "Heatmaps and session recordings showing real user behavior.", href: "https://hotjar.com", tags: ["analytics", "heatmaps", "paid", "free-tier", "ux"] },
      { name: "Canny", description: "Collect, organize, and prioritize user feature requests.", href: "https://canny.io", tags: ["feedback", "paid", "free-tier", "roadmap"] },
      { name: "Intercom", description: "In-app messaging to talk to users while they're in your product.", href: "https://intercom.com", tags: ["support", "chat", "paid", "customer-success"] },
      { name: "Tally", description: "Free Typeform alternative, beautiful forms, no limits.", href: "https://tally.so", tags: ["forms", "free", "surveys", "nocode"] },
      { name: "r/ChatGPTCoding", description: "AI dev community sharing real-world iteration stories.", href: "https://reddit.com/r/ChatGPTCoding", tags: ["community", "free", "reddit", "ai"] },
      { name: "Dub.co", description: "Short links with click tracking, see which CTAs actually convert.", href: "https://dub.co", tags: ["analytics", "links", "free-tier", "open-source", "marketing"] },
      { name: "ManyChat", description: "Auto-reply to Instagram comments and DMs, turn engagement into action.", href: "https://manychat.com", tags: ["instagram", "automation", "free-tier", "marketing", "dms"] },
      { name: "Google Play Console", description: "Where you publish, manage, and monitor Android apps on Google Play.", href: "https://play.google.com/console", tags: ["mobile", "android", "free", "publishing", "store"] },
      { name: "r/AndroidClosedTesting", description: "Best channel for recruiting closed-test users for Android apps.", href: "https://reddit.com/r/AndroidClosedTesting", tags: ["community", "free", "reddit", "android", "testing"] },
    ],
  },
  {
    slug: "backend",
    emoji: "🗄️",
    title: "Backend",
    description: "Databases, BaaS, and API infrastructure you'll need the moment your app has data.",
    items: [
      { name: "Supabase", description: "Postgres with auth, storage, realtime, and an instant REST API.", href: "https://supabase.com", tags: ["postgres", "auth", "storage", "realtime", "free-tier", "open-source"] },
      { name: "Neon", description: "Serverless Postgres that scales to zero, great for solo projects.", href: "https://neon.tech", tags: ["postgres", "serverless", "free-tier", "database"] },
      { name: "Convex", description: "Reactive backend-as-a-service with live queries and TypeScript-first DX.", href: "https://convex.dev", tags: ["realtime", "typescript", "paid", "free-tier", "baas"] },
      { name: "Turso", description: "Edge SQLite database, deployed close to your users globally.", href: "https://turso.tech", tags: ["sqlite", "edge", "paid", "free-tier", "database"] },
      { name: "PlanetScale", description: "MySQL-compatible serverless database with branching like Git.", href: "https://planetscale.com", tags: ["mysql", "serverless", "paid", "database", "branching"] },
      { name: "MongoDB Atlas", description: "Flexible document database with a generous free tier.", href: "https://mongodb.com/atlas", tags: ["nosql", "document", "free-tier", "database", "cloud"] },
      { name: "Firebase", description: "Google's BaaS, Firestore, Auth, Storage, and hosting in one.", href: "https://firebase.google.com", tags: ["google", "realtime", "free-tier", "baas", "auth"] },
      { name: "Upstash", description: "Serverless Redis for caching, rate limiting, and queues.", href: "https://upstash.com", tags: ["redis", "serverless", "free-tier", "caching", "queues"] },
      { name: "tRPC", description: "End-to-end typesafe APIs without schema generation.", href: "https://trpc.io", tags: ["typescript", "api", "open-source", "free", "typesafe"] },
      { name: "Hono", description: "Ultrafast edge-ready web framework, works on Cloudflare Workers.", href: "https://hono.dev", tags: ["edge", "api", "open-source", "free", "typescript", "cloudflare"] },
      { name: "Directus", description: "Headless CMS that wraps any SQL database with a REST/GraphQL API.", href: "https://directus.io", tags: ["cms", "headless", "open-source", "free-tier", "graphql"] },
      { name: "Hasura", description: "Instant GraphQL API over your existing Postgres database.", href: "https://hasura.io", tags: ["graphql", "postgres", "free-tier", "api"] },
    ],
  },
  {
    slug: "monetization",
    emoji: "💳",
    title: "Monetization",
    description: "Accept payments, manage subscriptions, and handle tax compliance from day one.",
    items: [
      { name: "Stripe", description: "The default payments API, subscriptions, one-time, invoicing.", href: "https://stripe.com", tags: ["payments", "subscriptions", "api", "free-tier", "invoicing"] },
      { name: "Lemon Squeezy", description: "Merchant of record, handles VAT and global tax so you don't have to.", href: "https://lemonsqueezy.com", tags: ["payments", "tax", "saas", "digital-products", "mor"] },
      { name: "Paddle", description: "MoR with global tax compliance, great for SaaS with international users.", href: "https://paddle.com", tags: ["payments", "tax", "saas", "subscriptions", "mor"] },
      { name: "Polar.sh", description: "Open-source monetization built for developers and OSS projects.", href: "https://polar.sh", tags: ["open-source", "payments", "free", "developers", "oss"] },
      { name: "Gumroad", description: "Sell digital products instantly with no code, great for early validation.", href: "https://gumroad.com", tags: ["digital-products", "free-tier", "simple", "nocode"] },
      { name: "Whop", description: "Sell access to communities, courses, SaaS, and digital products.", href: "https://whop.com", tags: ["communities", "digital-products", "saas", "courses"] },
      { name: "Chargebee", description: "Subscription billing management and revenue recovery at scale.", href: "https://chargebee.com", tags: ["subscriptions", "billing", "paid", "revenue"] },
      { name: "RevenueCat", description: "In-app purchase and subscription infrastructure for mobile apps.", href: "https://revenuecat.com", tags: ["mobile", "subscriptions", "ios", "android", "paid"] },
      { name: "Lago", description: "Open-source metered billing, usage-based pricing done right.", href: "https://getlago.com", tags: ["usage-based", "open-source", "billing", "free", "metered"] },
    ],
  },
  {
    slug: "auth",
    emoji: "🔐",
    title: "Auth",
    description: "Authentication, authorization, and identity, don't build this yourself.",
    items: [
      { name: "Auth.js", description: "Open-source authentication for Next.js and other frameworks.", href: "https://authjs.dev", tags: ["open-source", "free", "next-js", "oauth", "social-login"] },
      { name: "Supabase Auth", description: "Built-in auth in Supabase, email, OAuth, magic link, phone.", href: "https://supabase.com/auth", tags: ["oauth", "magic-link", "free-tier", "email", "phone"] },
      { name: "WorkOS", description: "Enterprise SSO, SCIM, and audit logs, one API for all of it.", href: "https://workos.com", tags: ["enterprise", "sso", "saml", "paid", "scim"] },
      { name: "Kinde", description: "Auth with a generous free tier, built for modern web apps.", href: "https://kinde.com", tags: ["free-tier", "oauth", "social-login", "paid"] },
      { name: "Lucia", description: "Lightweight auth library, total control, no magic.", href: "https://lucia-auth.com", tags: ["open-source", "free", "lightweight", "typescript"] },
      { name: "Better Auth", description: "Comprehensive TypeScript auth framework, framework-agnostic.", href: "https://better-auth.com", tags: ["typescript", "open-source", "free", "framework-agnostic"] },
      { name: "Stytch", description: "Passwordless auth, magic links, passkeys, OTP, with fraud protection.", href: "https://stytch.com", tags: ["passwordless", "passkeys", "paid", "free-tier", "magic-link"] },
    ],
  },
  {
    slug: "email",
    emoji: "✉️",
    title: "Email",
    description: "Transactional email, newsletters, and marketing sends for your app.",
    items: [
      { name: "Resend", description: "Developer-first transactional email with React email templates.", href: "https://resend.com", tags: ["transactional", "api", "developer", "free-tier", "react"] },
      { name: "Loops", description: "Email for SaaS, transactional and marketing in one platform.", href: "https://loops.so", tags: ["saas", "transactional", "marketing", "paid"] },
      { name: "Postmark", description: "Reliable transactional email with fast delivery and detailed analytics.", href: "https://postmarkapp.com", tags: ["transactional", "reliable", "paid", "free-tier", "analytics"] },
      { name: "SendGrid", description: "High-volume email infrastructure with marketing and transactional APIs.", href: "https://sendgrid.com", tags: ["high-volume", "marketing", "paid", "free-tier", "api"] },
      { name: "Mailchimp", description: "Marketing email and audience management, with a free tier.", href: "https://mailchimp.com", tags: ["marketing", "newsletter", "free-tier", "automation"] },
      { name: "React Email", description: "Build HTML emails with React components, works with any provider.", href: "https://react.email", tags: ["open-source", "free", "react", "templates", "html"] },
      { name: "Brevo", description: "Email + SMS + WhatsApp marketing, affordable and EU-based.", href: "https://brevo.com", tags: ["marketing", "sms", "eu", "free-tier", "whatsapp"] },
    ],
  },
  {
    slug: "ops-maintenance",
    emoji: "⚙️",
    title: "Iterate",
    description: "Observability, reliability, and ops after you ship.",
    items: [
      { name: "BetterStack", description: "Uptime monitoring, log management, and incident alerts.", href: "https://betterstack.com", tags: ["monitoring", "uptime", "alerts", "paid", "free-tier"] },
      { name: "Axiom", description: "Structured log management built for modern serverless apps.", href: "https://axiom.co", tags: ["logging", "serverless", "paid", "free-tier", "observability"] },
      { name: "Datadog", description: "Infrastructure and application monitoring at scale.", href: "https://datadog.com", tags: ["monitoring", "infrastructure", "paid", "apm", "observability"] },
      { name: "Umami", description: "Open-source, self-hostable privacy-friendly web analytics.", href: "https://umami.is", tags: ["analytics", "open-source", "self-hosted", "free", "privacy"] },
      { name: "GitHub Actions", description: "Automate workflows, deploys, and maintenance tasks.", href: "https://github.com/features/actions", tags: ["ci-cd", "automation", "free-tier", "github", "deployment"] },
      { name: "Cloudflare", description: "DDoS protection, caching, and edge networking at scale.", href: "https://cloudflare.com", tags: ["cdn", "security", "edge", "free-tier", "ddos"] },
    ],
  },
] as const satisfies readonly AwesomeCategory[];
